openapi: 3.0.1
info:
  title: monster-mind-flayer
  x-cortex-tag: monster-mind-flayer
  x-cortex-custom-metadata:
    alignment: lawful-good
    type: plant
    challenge_rating: 3
    legendary: false
    armor_class: 18
    hit_points: 98
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-mind-flayer
      alias: github-token-test
